app = "acqua"
primary_region = "lax"

[build]

[env]

[http_service]
internal_port = 8080
force_https = false
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
max_machines_running = 1

[[services]]
protocol = "tcp"
internal_port = 1234

  [[services.ports]]
  port = 22
  handlers = []

  [[services.ports]]
  port = 1234
  handlers = []

[[services]]
protocol = "tcp"
internal_port = 8080

  [[services.ports]]
  port = 8080
  handlers = []

[vm]
cpu_kind = "shared"
cpus = 1
memory_mb = 256